#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2025 MediaTek Inc.
#

STOP=21
USE_PROCD=1

shutdown() {
	/etc/init.d/prplmesh shutdown
	/etc/init.d/prplmesh_whm shutdown
}
